{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>\"Warkop ARKEN\"</td>\n",
       "      <td>-7.45383</td>\n",
       "      <td>112.4397</td>\n",
       "      <td>Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\"Warkop Dua putri\" Condong</td>\n",
       "      <td>-7.41148</td>\n",
       "      <td>112.4741</td>\n",
       "      <td>Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>\"warkop harmoni sadewa\"</td>\n",
       "      <td>-7.57251</td>\n",
       "      <td>112.3796</td>\n",
       "      <td>Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>\"Warkop serut\"</td>\n",
       "      <td>-7.48174</td>\n",
       "      <td>112.4132</td>\n",
       "      <td>Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>\"Wid\" Bengkel Motor Dan Warkop Wifi</td>\n",
       "      <td>-7.40019</td>\n",
       "      <td>112.4235</td>\n",
       "      <td>Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Nama Warkop      Lat      Long  \\\n",
       "0                       \"Warkop ARKEN\" -7.45383  112.4397   \n",
       "1           \"Warkop Dua putri\" Condong -7.41148  112.4741   \n",
       "2              \"warkop harmoni sadewa\" -7.57251  112.3796   \n",
       "3                       \"Warkop serut\" -7.48174  112.4132   \n",
       "4  \"Wid\" Bengkel Motor Dan Warkop Wifi -7.40019  112.4235   \n",
       "\n",
       "                                              Alamat Kab/Kota  \n",
       "0  Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...      Kab  \n",
       "1  Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...      Kab  \n",
       "2  Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...      Kab  \n",
       "3  Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...      Kab  \n",
       "4  Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...      Kab  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "data = pd.read_csv(\"Merge_CSV_MJK_akancleanse.csv\",encoding= 'unicode_escape')\n",
    "\n",
    "data.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>\"Warkop ARKEN\"</td>\n",
       "      <td>-7.45383</td>\n",
       "      <td>112.4397</td>\n",
       "      <td>Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\"Warkop Dua putri\" Condong</td>\n",
       "      <td>-7.41148</td>\n",
       "      <td>112.4741</td>\n",
       "      <td>Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>\"warkop harmoni sadewa\"</td>\n",
       "      <td>-7.57251</td>\n",
       "      <td>112.3796</td>\n",
       "      <td>Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>\"Warkop serut\"</td>\n",
       "      <td>-7.48174</td>\n",
       "      <td>112.4132</td>\n",
       "      <td>Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>\"Wid\" Bengkel Motor Dan Warkop Wifi</td>\n",
       "      <td>-7.40019</td>\n",
       "      <td>112.4235</td>\n",
       "      <td>Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Nama Warkop      Lat      Long  \\\n",
       "0                       \"Warkop ARKEN\" -7.45383  112.4397   \n",
       "1           \"Warkop Dua putri\" Condong -7.41148  112.4741   \n",
       "2              \"warkop harmoni sadewa\" -7.57251  112.3796   \n",
       "3                       \"Warkop serut\" -7.48174  112.4132   \n",
       "4  \"Wid\" Bengkel Motor Dan Warkop Wifi -7.40019  112.4235   \n",
       "\n",
       "                                              Alamat Kab/Kota  \n",
       "0  Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...      Kab  \n",
       "1  Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...      Kab  \n",
       "2  Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...      Kab  \n",
       "3  Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...      Kab  \n",
       "4  Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...      Kab  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data2 = data.dropna()\n",
    "\n",
    "data2.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>\"Warkop ARKEN\"</td>\n",
       "      <td>-7.45383</td>\n",
       "      <td>112.4397</td>\n",
       "      <td>Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\"Warkop Dua putri\" Condong</td>\n",
       "      <td>-7.41148</td>\n",
       "      <td>112.4741</td>\n",
       "      <td>Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>\"Warkop serut\"</td>\n",
       "      <td>-7.48174</td>\n",
       "      <td>112.4132</td>\n",
       "      <td>Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>\"Wid\" Bengkel Motor Dan Warkop Wifi</td>\n",
       "      <td>-7.40019</td>\n",
       "      <td>112.4235</td>\n",
       "      <td>Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Artyan Warkop Badak e Free Wifi</td>\n",
       "      <td>-7.61158</td>\n",
       "      <td>112.5313</td>\n",
       "      <td>Raya Simpang tiga Pandan, Pandan, Pandanarum, ...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                            Nama Warkop      Lat      Long  \\\n",
       "0                        \"Warkop ARKEN\" -7.45383  112.4397   \n",
       "1            \"Warkop Dua putri\" Condong -7.41148  112.4741   \n",
       "3                        \"Warkop serut\" -7.48174  112.4132   \n",
       "4   \"Wid\" Bengkel Motor Dan Warkop Wifi -7.40019  112.4235   \n",
       "12      Artyan Warkop Badak e Free Wifi -7.61158  112.5313   \n",
       "\n",
       "                                               Alamat Kab/Kota  \n",
       "0   Jl. Raya Kenongo, RT.04/RW.01, Lorsari, Mlirip...      Kab  \n",
       "1   Unnamed Road, Jetis, Kec. Jetis, Mojokerto, Ja...      Kab  \n",
       "3   Unnamed Road, Mergelo, Mergelo, Blooto, Kec. P...      Kab  \n",
       "4   Jl. Raya Tugu No.147, Tugu, Kupang, Kec. Jetis...      Kab  \n",
       "12  Raya Simpang tiga Pandan, Pandan, Pandanarum, ...      Kab  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data3 = data2[data2['Nama Warkop'].str.contains('Warkop')]\n",
    "               \n",
    "data3.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "data3.to_csv ('warkop1_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>\"warkop harmoni sadewa\"</td>\n",
       "      <td>-7.57251</td>\n",
       "      <td>112.3796</td>\n",
       "      <td>Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Bescem(warkop Soehardie)</td>\n",
       "      <td>-7.50195</td>\n",
       "      <td>112.5089</td>\n",
       "      <td>Pendowo, Ngrowo, Bangsal, Mojokerto, East Java...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Coblok warkop</td>\n",
       "      <td>-7.58413</td>\n",
       "      <td>112.4445</td>\n",
       "      <td>Jl. Raya Desa Mojogeneng, Jetis, Mojogeneng, J...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>D'warkop</td>\n",
       "      <td>-7.40824</td>\n",
       "      <td>112.4736</td>\n",
       "      <td>Jl. Raya Jetis, Jetis, Canggu, Kec. Jetis, Moj...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>61</th>\n",
       "      <td>Heloise band(warkop)</td>\n",
       "      <td>-7.52103</td>\n",
       "      <td>112.5312</td>\n",
       "      <td>Heloise band, Sumbertanggul, Kec. Mojosari, Mo...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Nama Warkop      Lat      Long  \\\n",
       "2    \"warkop harmoni sadewa\" -7.57251  112.3796   \n",
       "26  Bescem(warkop Soehardie) -7.50195  112.5089   \n",
       "35             Coblok warkop -7.58413  112.4445   \n",
       "46                  D'warkop -7.40824  112.4736   \n",
       "61      Heloise band(warkop) -7.52103  112.5312   \n",
       "\n",
       "                                               Alamat Kab/Kota  \n",
       "2   Kedaton, Sentonorejo, Trowulan, Mojokerto, Eas...      Kab  \n",
       "26  Pendowo, Ngrowo, Bangsal, Mojokerto, East Java...      Kab  \n",
       "35  Jl. Raya Desa Mojogeneng, Jetis, Mojogeneng, J...      Kab  \n",
       "46  Jl. Raya Jetis, Jetis, Canggu, Kec. Jetis, Moj...      Kab  \n",
       "61  Heloise band, Sumbertanggul, Kec. Mojosari, Mo...      Kab  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data4 = data2[data2['Nama Warkop'].str.contains('warkop')]\n",
    "               \n",
    "data4.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "data4.to_csv ('warkop2_MJK3.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>ANGKRINGAN BARNET (WARKOP HERBAL)</td>\n",
       "      <td>-7.53261</td>\n",
       "      <td>112.4073</td>\n",
       "      <td>Jl. Lengkong, Bengkong, Jambuwok, Kec. Trowula...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>BROFELLAZ WARKOP &amp; POMADESTORE</td>\n",
       "      <td>-7.49521</td>\n",
       "      <td>112.4600</td>\n",
       "      <td>Jl. Gempol - Mojokerto No.158, Jabon, Kec. Moj...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>DIIK WARKOP WIFI</td>\n",
       "      <td>-7.54673</td>\n",
       "      <td>112.5232</td>\n",
       "      <td>Pandisari, Sumber Jati, Sawo, Kec. Kutorejo, M...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>ECO WARKOP 88</td>\n",
       "      <td>-7.41702</td>\n",
       "      <td>112.3984</td>\n",
       "      <td>Jl. Mojokerto-Lamongan, Japanan Kidul, Japanan...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>FORESTER WARKOP</td>\n",
       "      <td>-7.45658</td>\n",
       "      <td>112.4309</td>\n",
       "      <td>Jl. Raya Sidoharjo, Terusan, Kec. Gedek, Mojok...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                          Nama Warkop      Lat      Long  \\\n",
       "9   ANGKRINGAN BARNET (WARKOP HERBAL) -7.53261  112.4073   \n",
       "27     BROFELLAZ WARKOP & POMADESTORE -7.49521  112.4600   \n",
       "41                   DIIK WARKOP WIFI -7.54673  112.5232   \n",
       "47                      ECO WARKOP 88 -7.41702  112.3984   \n",
       "51                    FORESTER WARKOP -7.45658  112.4309   \n",
       "\n",
       "                                               Alamat Kab/Kota  \n",
       "9   Jl. Lengkong, Bengkong, Jambuwok, Kec. Trowula...      Kab  \n",
       "27  Jl. Gempol - Mojokerto No.158, Jabon, Kec. Moj...      Kab  \n",
       "41  Pandisari, Sumber Jati, Sawo, Kec. Kutorejo, M...      Kab  \n",
       "47  Jl. Mojokerto-Lamongan, Japanan Kidul, Japanan...      Kab  \n",
       "51  Jl. Raya Sidoharjo, Terusan, Kec. Gedek, Mojok...      Kab  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data5 = data2[data2['Nama Warkop'].str.contains('WARKOP')]\n",
    "               \n",
    "data5.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "data5.to_csv ('warkop3_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1819</th>\n",
       "      <td>warung kopi, nasi jagung 'emak yah'</td>\n",
       "      <td>-7.6448</td>\n",
       "      <td>112.6209</td>\n",
       "      <td>Bantal, Duyung, Trawas, Mojokerto, East Java 6...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                              Nama Warkop     Lat      Long  \\\n",
       "1819  warung kopi, nasi jagung 'emak yah' -7.6448  112.6209   \n",
       "\n",
       "                                                 Alamat Kab/Kota  \n",
       "1819  Bantal, Duyung, Trawas, Mojokerto, East Java 6...      Kab  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data6 = data2[data2['Nama Warkop'].str.contains('warung kopi')]\n",
    "               \n",
    "data6.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "data6.to_csv ('warkop4_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>187</th>\n",
       "      <td>Wako Warung Kopi</td>\n",
       "      <td>-7.48932</td>\n",
       "      <td>112.4208</td>\n",
       "      <td>Perum Citra Surodinawan, Jl. Suromulang No.46,...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1813</th>\n",
       "      <td>Warung Kopi Bonan</td>\n",
       "      <td>-7.66773</td>\n",
       "      <td>112.6072</td>\n",
       "      <td>Jl. Raya Trawas, RT.04/RW.02, Sukorame, Ketapa...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1814</th>\n",
       "      <td>Warung Kopi Mak Ni</td>\n",
       "      <td>-7.54079</td>\n",
       "      <td>112.3886</td>\n",
       "      <td>Dsn Wringin Lawang, Lawang, Jatipasar, Kec. Tr...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1815</th>\n",
       "      <td>Warung Kopi Mak Yati</td>\n",
       "      <td>-7.53777</td>\n",
       "      <td>112.4435</td>\n",
       "      <td>Jl. Raya Puri, RT.2/RW.2, Sawo, Kec. Puri, Moj...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1816</th>\n",
       "      <td>Warung Kopi Mbok Biyah</td>\n",
       "      <td>-7.42891</td>\n",
       "      <td>112.3986</td>\n",
       "      <td>Jeruk Seger, Jerukseger, Kec. Gedek, Mojokerto...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Nama Warkop      Lat      Long  \\\n",
       "187         Wako Warung Kopi -7.48932  112.4208   \n",
       "1813       Warung Kopi Bonan -7.66773  112.6072   \n",
       "1814      Warung Kopi Mak Ni -7.54079  112.3886   \n",
       "1815    Warung Kopi Mak Yati -7.53777  112.4435   \n",
       "1816  Warung Kopi Mbok Biyah -7.42891  112.3986   \n",
       "\n",
       "                                                 Alamat Kab/Kota  \n",
       "187   Perum Citra Surodinawan, Jl. Suromulang No.46,...      Kab  \n",
       "1813  Jl. Raya Trawas, RT.04/RW.02, Sukorame, Ketapa...      Kab  \n",
       "1814  Dsn Wringin Lawang, Lawang, Jatipasar, Kec. Tr...      Kab  \n",
       "1815  Jl. Raya Puri, RT.2/RW.2, Sawo, Kec. Puri, Moj...      Kab  \n",
       "1816  Jeruk Seger, Jerukseger, Kec. Gedek, Mojokerto...      Kab  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data7 = data2[data2['Nama Warkop'].str.contains('Warung Kopi')]\n",
    "               \n",
    "data7.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "data7.to_csv ('warkop5_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1812</th>\n",
       "      <td>Warung kopi Barokah Free Wifi</td>\n",
       "      <td>-7.5601</td>\n",
       "      <td>112.4811</td>\n",
       "      <td>Jl. Jendral Ahmad Yani No.34, Kasian, Pohkecik...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                        Nama Warkop     Lat      Long  \\\n",
       "1812  Warung kopi Barokah Free Wifi -7.5601  112.4811   \n",
       "\n",
       "                                                 Alamat Kab/Kota  \n",
       "1812  Jl. Jendral Ahmad Yani No.34, Kasian, Pohkecik...      Kab  "
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data8 = data2[data2['Nama Warkop'].str.contains('Warung kopi')]\n",
    "               \n",
    "data8.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "data8.to_csv ('Warkop6_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>784</th>\n",
       "      <td>Warkop giras 56</td>\n",
       "      <td>-7.42516</td>\n",
       "      <td>112.3725</td>\n",
       "      <td>Berat Kidul, Beratkulon, Kemlagi, Mojokerto, E...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Nama Warkop      Lat      Long  \\\n",
       "784  Warkop giras 56 -7.42516  112.3725   \n",
       "\n",
       "                                                Alamat Kab/Kota  \n",
       "784  Berat Kidul, Beratkulon, Kemlagi, Mojokerto, E...      Kab  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data9 = data2[data2['Nama Warkop'].str.contains('giras')]\n",
    "               \n",
    "data9.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "data9.to_csv ('Warkop7_MJK2.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Nama Warkop</th>\n",
       "      <th>Lat</th>\n",
       "      <th>Long</th>\n",
       "      <th>Alamat</th>\n",
       "      <th>Kab/Kota</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>59</th>\n",
       "      <td>Giras Warkop Dki Badaks</td>\n",
       "      <td>-7.49524</td>\n",
       "      <td>112.4597</td>\n",
       "      <td>Jl. Gempol - Mojokerto No.158, Jabon, Kec. Moj...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>181</th>\n",
       "      <td>Toko &amp; Warkop Giras</td>\n",
       "      <td>-7.49945</td>\n",
       "      <td>112.4392</td>\n",
       "      <td>Jl. Raya By Pass No.10, Sumber Gayam, Kenanten...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>780</th>\n",
       "      <td>Warkop Giras \"UP\"</td>\n",
       "      <td>-7.53318</td>\n",
       "      <td>112.5545</td>\n",
       "      <td>Jl. Hasanuddin No.194, Candirejo, Awang Awang,...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>782</th>\n",
       "      <td>Warkop Giras 27</td>\n",
       "      <td>-7.34762</td>\n",
       "      <td>112.4246</td>\n",
       "      <td>Jl. Raya Jatirowo No.25, Jatirowo, Dawar Bland...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>783</th>\n",
       "      <td>Warkop Giras 473</td>\n",
       "      <td>-7.46578</td>\n",
       "      <td>112.5151</td>\n",
       "      <td>Jl. Raya Tarik, RT.14/RW.04, Tarik Kidul, Tari...</td>\n",
       "      <td>Kab</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Nama Warkop      Lat      Long  \\\n",
       "59   Giras Warkop Dki Badaks -7.49524  112.4597   \n",
       "181      Toko & Warkop Giras -7.49945  112.4392   \n",
       "780        Warkop Giras \"UP\" -7.53318  112.5545   \n",
       "782          Warkop Giras 27 -7.34762  112.4246   \n",
       "783         Warkop Giras 473 -7.46578  112.5151   \n",
       "\n",
       "                                                Alamat Kab/Kota  \n",
       "59   Jl. Gempol - Mojokerto No.158, Jabon, Kec. Moj...      Kab  \n",
       "181  Jl. Raya By Pass No.10, Sumber Gayam, Kenanten...      Kab  \n",
       "780  Jl. Hasanuddin No.194, Candirejo, Awang Awang,...      Kab  \n",
       "782  Jl. Raya Jatirowo No.25, Jatirowo, Dawar Bland...      Kab  \n",
       "783  Jl. Raya Tarik, RT.14/RW.04, Tarik Kidul, Tari...      Kab  "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data10 = data2[data2['Nama Warkop'].str.contains('Giras')]\n",
    "               \n",
    "data10.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "data10.to_csv ('warkop8_MJK2.csv')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
